- hosts: webservers
  tasks:
  - name: create manifest template for kube deploy 
    template:
      src: "/kubernetes.yml"
      dest: "root/kubernetes.yml"
      register: deploy_template

    # Applys 
  - name: apply kubernetes deployment
    shell: "kubectl apply -f root/kubernetes.yml"