- hosts: webservers
  become: yes
  become_user: root
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: ./kubernetes.yml
      dest: /root/kubernetes.yml
  - name: delete the previous of kubernetes objects 
    command: kubectl delete -f /root/kubernetes.yml
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /root/kubernetes.yml