- hosts: webservers
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: kubernetes.yml
      dest: /home/ec2-user/root
  - name: delete the previous of kubernetes objects 
    command: kubectl delete -f /home/ec2-user/root/kubernetes.yml
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /home/ec2-user/root/kubernetes.yml