- hosts: webservers
  become_user: root
  tasks: 
    - name: Copy kubernetes YAML
      ansible.builtin.copy:
        src: /kubernetes.yml
        dest: /etc/kubernetes.yml
        owner: root
        mode: 7777
    - name: Start minikube
      command: minikube Start
    - name: Apply kubernetes YAML
      command: kubetcl create -f /kubernetes.yml